# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dm1-3266\PycharmProjects\momentum_crossovers_backtest\lib\ui\MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(950, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.figure_widget = QtGui.QWidget(self.centralwidget)
        self.figure_widget.setGeometry(QtCore.QRect(0, 0, 950, 450))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figure_widget.sizePolicy().hasHeightForWidth())
        self.figure_widget.setSizePolicy(sizePolicy)
        self.figure_widget.setMaximumSize(QtCore.QSize(950, 450))
        self.figure_widget.setObjectName(_fromUtf8("figure_widget"))
        self.groupBox_type = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_type.setGeometry(QtCore.QRect(10, 460, 120, 91))
        self.groupBox_type.setObjectName(_fromUtf8("groupBox_type"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_type)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.momentumButton = QtGui.QRadioButton(self.layoutWidget)
        self.momentumButton.setChecked(True)
        self.momentumButton.setObjectName(_fromUtf8("momentumButton"))
        self.verticalLayout_2.addWidget(self.momentumButton, QtCore.Qt.AlignLeft)
        self.crossoversButton = QtGui.QRadioButton(self.layoutWidget)
        self.crossoversButton.setObjectName(_fromUtf8("crossoversButton"))
        self.verticalLayout_2.addWidget(self.crossoversButton)
        self.groupBox_index = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_index.setGeometry(QtCore.QRect(140, 455, 120, 101))
        self.groupBox_index.setObjectName(_fromUtf8("groupBox_index"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_index)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 101, 71))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(10, 2, 5, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.index300Button = QtGui.QRadioButton(self.layoutWidget1)
        self.index300Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.index300Button.setChecked(True)
        self.index300Button.setObjectName(_fromUtf8("index300Button"))
        self.verticalLayout.addWidget(self.index300Button)
        self.index500Button = QtGui.QRadioButton(self.layoutWidget1)
        self.index500Button.setObjectName(_fromUtf8("index500Button"))
        self.verticalLayout.addWidget(self.index500Button, QtCore.Qt.AlignLeft)
        self.index800Button = QtGui.QRadioButton(self.layoutWidget1)
        self.index800Button.setObjectName(_fromUtf8("index800Button"))
        self.verticalLayout.addWidget(self.index800Button, QtCore.Qt.AlignLeft)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(270, 460, 201, 91))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_3.setMargin(5)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label, QtCore.Qt.AlignHCenter)
        self.periodSlider = QtGui.QSlider(self.layoutWidget2)
        self.periodSlider.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodSlider.sizePolicy().hasHeightForWidth())
        self.periodSlider.setSizePolicy(sizePolicy)
        self.periodSlider.setMinimumSize(QtCore.QSize(160, 0))
        self.periodSlider.setMaximumSize(QtCore.QSize(172, 16777215))
        self.periodSlider.setMinimum(1)
        self.periodSlider.setMaximum(6)
        self.periodSlider.setPageStep(1)
        self.periodSlider.setOrientation(QtCore.Qt.Horizontal)
        self.periodSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.periodSlider.setTickInterval(1)
        self.periodSlider.setObjectName(_fromUtf8("periodSlider"))
        self.verticalLayout_3.addWidget(self.periodSlider)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_percent = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_percent.setGeometry(QtCore.QRect(480, 455, 151, 91))
        self.groupBox_percent.setObjectName(_fromUtf8("groupBox_percent"))
        self.checkBoxP5 = QtGui.QCheckBox(self.groupBox_percent)
        self.checkBoxP5.setGeometry(QtCore.QRect(60, 30, 31, 16))
        self.checkBoxP5.setObjectName(_fromUtf8("checkBoxP5"))
        self.checkBoxP10 = QtGui.QCheckBox(self.groupBox_percent)
        self.checkBoxP10.setGeometry(QtCore.QRect(110, 30, 41, 16))
        self.checkBoxP10.setObjectName(_fromUtf8("checkBoxP10"))
        self.checkBoxP1 = QtGui.QCheckBox(self.groupBox_percent)
        self.checkBoxP1.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.checkBoxP1.setChecked(True)
        self.checkBoxP1.setObjectName(_fromUtf8("checkBoxP1"))
        self.checkBoxP20 = QtGui.QCheckBox(self.groupBox_percent)
        self.checkBoxP20.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.checkBoxP20.setObjectName(_fromUtf8("checkBoxP20"))
        self.checkBoxP30 = QtGui.QCheckBox(self.groupBox_percent)
        self.checkBoxP30.setGeometry(QtCore.QRect(60, 60, 41, 16))
        self.checkBoxP30.setObjectName(_fromUtf8("checkBoxP30"))
        self.textReturn = QtGui.QTextBrowser(self.centralwidget)
        self.textReturn.setGeometry(QtCore.QRect(790, 460, 150, 90))
        self.textReturn.setObjectName(_fromUtf8("textReturn"))
        self.groupBox_returntype = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_returntype.setGeometry(QtCore.QRect(640, 460, 141, 91))
        self.groupBox_returntype.setObjectName(_fromUtf8("groupBox_returntype"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_returntype)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 117, 61))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_4.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.periodReturnButton = QtGui.QRadioButton(self.layoutWidget_2)
        self.periodReturnButton.setChecked(True)
        self.periodReturnButton.setObjectName(_fromUtf8("periodReturnButton"))
        self.verticalLayout_4.addWidget(self.periodReturnButton, QtCore.Qt.AlignLeft)
        self.cumReturnButton = QtGui.QRadioButton(self.layoutWidget_2)
        self.cumReturnButton.setObjectName(_fromUtf8("cumReturnButton"))
        self.verticalLayout_4.addWidget(self.cumReturnButton)
        self.layoutWidget.raise_()
        self.groupBox_type.raise_()
        self.figure_widget.raise_()
        self.groupBox_index.raise_()
        self.groupBox_percent.raise_()
        self.textReturn.raise_()
        self.groupBox_returntype.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.groupBox_type.setTitle(_translate("MainWindow", "效应类型", None))
        self.momentumButton.setText(_translate("MainWindow", "动量效应", None))
        self.crossoversButton.setText(_translate("MainWindow", "反转效应", None))
        self.groupBox_index.setTitle(_translate("MainWindow", "指数类型", None))
        self.index300Button.setText(_translate("MainWindow", "沪深300", None))
        self.index500Button.setText(_translate("MainWindow", "中证500", None))
        self.index800Button.setText(_translate("MainWindow", "中证800", None))
        self.label.setText(_translate("MainWindow", "计算收益率时间长度（月）", None))
        self.label_3.setText(_translate("MainWindow", "1", None))
        self.label_2.setText(_translate("MainWindow", "2", None))
        self.label_4.setText(_translate("MainWindow", "3", None))
        self.label_5.setText(_translate("MainWindow", "4", None))
        self.label_6.setText(_translate("MainWindow", "5", None))
        self.label_7.setText(_translate("MainWindow", "6", None))
        self.groupBox_percent.setTitle(_translate("MainWindow", "组合占比", None))
        self.checkBoxP5.setText(_translate("MainWindow", "5%", None))
        self.checkBoxP10.setText(_translate("MainWindow", "10%", None))
        self.checkBoxP1.setText(_translate("MainWindow", "1%", None))
        self.checkBoxP20.setText(_translate("MainWindow", "20%", None))
        self.checkBoxP30.setText(_translate("MainWindow", "30%", None))
        self.groupBox_returntype.setTitle(_translate("MainWindow", "超额收益率类型", None))
        self.periodReturnButton.setText(_translate("MainWindow", "分期超额收益率", None))
        self.cumReturnButton.setText(_translate("MainWindow", "累计超额收益率", None))

